-- initialize swarm
-- plant and grow a tree
-- order swarm to refuel
--- decide tree, get bonemeal, get sapling
-- while y of swarm is less then max_y
-- order swarm to perform 1 routine
-- wait for swarm to finish
-- increment y of swarm
-- repeat
-- 